---
title: "statar"
author: "Matthieu Gomez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Join}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---




## Join
`join` is a wrapper for data.table merge functionalities.

- The option "kind" specifies the kind of join based on SQL syntax. Possible kinds are : left, right, inner, outer, semi, anti and cross.

  |Stata     | statar
  |:-----------|------------
  |merge v1   | join(x, y, kind = "outer") 
  |merge v1, keep(master matched)  |  join(x, y, kind = "left")
  |merge v1, keep(matched using)  | join(x, y, kind = "right")
  |merge v1, keep(matched)| join(x, y, kind = "inner")
  |merge v1, keep(matched) keepusing(v1)| join(x, y, kind = "semi")
  |merge v1, keep(master) keepusing(v1)| join(x, y, kind = "anti")
  |crossby   | join(x, y, kind = "cross")

- The option "check" checks there are no duplicates in the master or using data.tables (as in Stata).

  ```r
  # merge m:1 v1
  join(x, y, kind = "outer", check = m~1) 
  ```
- The option "gen" specifies the name of a new variable that identifies non matched and matched rows (as in Stata).

  ```r
  # merge m:1 v1, gen(_merge) 
  join(x, y, kind = "outer", gen = "_merge") 
  ```


- The option "inplace" specifies whether the dataset x should be merged in place. It is only available for left joins, when y has no duplicates (for now).


## Fuzzy Join
`fuzzy_join`  uses record linkage methods to match observations between two datasets where no perfect key fields exist. For each row in x, fuzzy_join finds the row(s) in y with the lowest distance (a weighted average of the string distance defined in method over multiple columns).

It corresponds roughtly to `reclink`, except that rows in `y` are not thrown away after an exact match with `x`.

One can specify

- Columns on which to match exactly
- Columns on which to match fuzzily
- Weight across multiple colums
- Kind of string distance used

```R
x <- data.table(x = c("france", "franc"), y = c("arras", "dijon"))
y <- data.table(x = c("franc", "france"), y = c("arvars", "dijjon"))
fuzzy_join(x, y, fuzzy = c("x", "y"))
fuzzy_join(x, y, fuzzy = c("x", "y"), w = c(0.9, 0.1))
fuzzy_join(x,y, fuzzy = c("x", "y"), w = c(0, 0.9))
x <- data.table(x = c(1, 1), y = c("arras", "dijon"))
y <- data.table(x = c(1, 1), y = c("arvars", "dijjon"))
fuzzy_join(x, y, exact = "x", fuzzy = "y")
x <- data.table(x = c(1, 2), y = c("arras", "dijon"))
y <- data.table(x = c(1, 1), y = c("arvars", "dijjon"))
fuzzy_join(x,y, exact = "x", fuzzy = "y")
```


